name = input("What is your name?\n")
print("Hello " + name + "!")
city = input(name + ", what is the name of the city you grew up in?\n")
pet_name = input(name + ", what is the name of your pet?\n")
print("Your band name should be " + city + " " + pet_name)
